# Generated by Django 5.2.7 on 2025-10-13 10:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Council',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_position', models.CharField(help_text='The role or position of the student in the council', max_length=200)),
                ('committee', models.CharField(help_text='The committee the student belongs to', max_length=200)),
                ('start_date', models.DateField(default=django.utils.timezone.now, help_text='The date the student started this council role')),
                ('end_date', models.DateField(blank=True, help_text='The date the student ended this council role (if applicable)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='council_positions', to='Student.student')),
            ],
            options={
                'verbose_name': 'Council Member',
                'verbose_name_plural': 'Council Members',
                'ordering': ['committee', 'role_position', 'student'],
            },
        ),
    ]
