# Generated by Django 5.2.7 on 2025-10-13 10:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CouncilMembers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouncilEventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_event', models.CharField(help_text='Role assigned to this council member in the event', max_length=200)),
                ('attended', models.BooleanField(default=False, help_text='Did the council member attend this event?')),
                ('council_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to='CouncilMembers.council')),
            ],
            options={
                'verbose_name': 'Council Event Participation',
                'verbose_name_plural': 'Council Event Participations',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Event title', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the event')),
                ('location', models.CharField(help_text='Event location', max_length=200)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, help_text='Start date and time of the event')),
                ('end_time', models.DateTimeField(blank=True, help_text='End date and time of the event', null=True)),
                ('speakers', models.JSONField(blank=True, default=list, help_text='List of speakers')),
                ('partners', models.JSONField(blank=True, default=list, help_text='List of partner organizations')),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Maximum number of participants', null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', help_text='Current status of the event', max_length=20)),
                ('registration_required', models.BooleanField(default=True, help_text='Is registration required to attend?')),
                ('registration_link', models.URLField(blank=True, help_text='Optional link for registration', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('council_members', models.ManyToManyField(related_name='events', through='Events.CouncilEventParticipation', to='CouncilMembers.council')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-time'],
            },
        ),
        migrations.AddField(
            model_name='councileventparticipation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='council_participations', to='Events.event'),
        ),
        migrations.AlterUniqueTogether(
            name='councileventparticipation',
            unique_together={('event', 'council_member')},
        ),
    ]
