# Generated by Django 5.2.6 on 2025-09-29 01:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='partners',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='event',
            name='speakers',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
