# Generated by Django 5.2.6 on 2025-09-29 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CouncilMemebers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='council',
            name='committee',
            field=models.CharField(default='main', max_length=200),
        ),
    ]
