# Generated by Django 5.2.6 on 2025-09-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CouncilMemebers', '0002_council_committee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='council',
            name='committee',
            field=models.CharField(max_length=200),
        ),
    ]
