# Generated by Django 5.2.7 on 2025-10-05 01:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=200)),
                ('reg_number', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=200)),
                ('year', models.DateTimeField(default=django.utils.timezone.now)),
                ('comments', models.TextField()),
            ],
        ),
    ]
