# Generated by Django 5.2.6 on 2025-09-29 00:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissions',
            name='year',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='admissions',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
