# Generated by Django 5.2.6 on 2025-09-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=200)),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('image', 'Image')], max_length=10)),
                ('media_file', models.FileField(upload_to='uploads/media/')),
            ],
        ),
    ]
