# Generated by Django 5.2.7 on 2025-10-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('event', 'Event'), ('lecture', 'Lecture'), ('announcement', 'Announcement')], default='event', max_length=50)),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('image', 'Image')], max_length=10)),
                ('media_file', models.FileField(upload_to='uploads/media/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media Files',
                'ordering': ['-created_at'],
            },
        ),
    ]
