# Generated by Django 5.2.6 on 2025-09-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventMedia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='Category',
            new_name='title',
        ),
        migrations.AddField(
            model_name='media',
            name='category',
            field=models.CharField(choices=[('event', 'Event'), ('lecture', 'Lecture'), ('announcement', 'Announcement')], default='event', max_length=50),
        ),
    ]
