# Generated by Django 5.2.7 on 2025-10-13 10:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('institution', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('attended', 'Attended'), ('cancelled', 'Cancelled')], default='registered', help_text='Current participation status', max_length=20)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when the non-member registered for the event')),
                ('attended_date', models.DateTimeField(blank=True, help_text='Date when the non-member actually attended', null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('certificate_issued', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('events', models.ManyToManyField(related_name='non_members', to='Events.event')),
            ],
            options={
                'verbose_name': 'Non-Member',
                'verbose_name_plural': 'Non-Members',
                'ordering': ['-created_at'],
            },
        ),
    ]
