# Generated by Django 5.2.7 on 2025-10-05 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admissions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admissions.admissions')),
            ],
        ),
    ]
