# Generated by Django 5.2.6 on 2025-09-29 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admissions', '0002_admissions_year_alter_admissions_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminssions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admissions.admissions')),
            ],
        ),
    ]
