# Generated by Django 5.2.7 on 2025-10-06 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admissions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='Admissions.admission')),
            ],
        ),
    ]
