# Generated by Django 5.2.6 on 2025-09-29 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='adminssions',
            new_name='admissions',
        ),
    ]
