# Generated by Django 5.2.6 on 2025-09-29 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Events', '0002_alter_event_partners_alter_event_speakers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('events', models.ManyToManyField(related_name='non_members', to='Events.event')),
            ],
        ),
    ]
