# Generated by Django 5.2.7 on 2025-10-13 10:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Events', '0001_initial'),
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When the student registered for the event')),
                ('attended_date', models.DateTimeField(blank=True, help_text='The actual date/time when the student attended', null=True)),
                ('status', models.CharField(choices=[('attended', 'Attended'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='missed', help_text='Status of attendance', max_length=20)),
                ('feedback', models.TextField(blank=True, help_text='Optional feedback from the student about the event', null=True)),
                ('certificate_issued', models.BooleanField(default=False, help_text='Whether a certificate of participation was issued')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='Events.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='Student.student')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'event')},
            },
        ),
    ]
